default_model_list = [{
        "name": "google/gemma-3-4b-it",
        "base_model": "google/gemma-3-4b-pt",
        "training_method": "Causal Language Modeling",
        "commit_msg": "Googel Gemma",
        "user_name": "google",
        "use_flash_attention": True,
    },
    {
        "name": "google/gemma-3-12b-it",
        "base_model": "google/gemma-3-12b-pt",
        "training_method": "Causal Language Modeling",
        "commit_msg": "Googel Gemma",
        "user_name": "google",
        "use_flash_attention": True,
    },
    {
        "name": "google/gemma-3-27b-it",
        "base_model": "google/gemma-3-27b-pt",
        "training_method": "Causal Language Modeling",
        "commit_msg": "Googel Gemma",
        "user_name": "google",
        "use_flash_attention": True,
    },
    {
        "name": "Qwen/Qwen3-4B",
        "base_model": "Qwen/Qwen3-4B-Base",
        "training_method": "Causal Language Modeling",
        "commit_msg": "Alibaba Qwen",
        "user_name": "Qwen",
        "use_flash_attention": True,
    },
    {
        "name": "Qwen/Qwen3-8B",
        "base_model": "Qwen/Qwen3-8B-Base",
        "training_method": "Causal Language Modeling",
        "commit_msg": "Alibaba Qwen",
        "user_name": "Qwen",
        "use_flash_attention": True,
    },
    {
        "name": "deepseek-ai/DeepSeek-R1-Distill-Qwen-7B",
        "training_method": "Causal Language Modeling",
        "commit_msg": "DeepSeek Qwen 7B",
        "user_name": "deepseek-ai",
        "use_flash_attention": True,
    },
    {
        "name": "meta-llama/Llama-3.2-3B-Instruct",
        "training_method": "Causal Language Modeling",
        "commit_msg": "Meta Lllama 3.2",
        "user_name": "meta-llama",
        "use_flash_attention": True,
    }
]